Калькулятор доходов и расходов
codecrafts/java.fundamentals pull request #106
Opened 2018-09-12 01:18 UTC by Zaqwesx

первая версия.
тесты пока under construction.

2018-09-14 11:31 UTC, michael-java reviewed
Не понял идею использования паттерна.
Вроде как смысл его в определении зависимости типа один ко многим между объектами, чтобы при изменении состояния одного объекта все зависящие от него оповещаются об этом событии...
Плюсом используем для:
- если один объект должен передавать сообщения другим объектам, но при этом он не может или не должен знать об их внутреннем устройстве;
- при изменении одного объекта необходимо изменять другие объекты;
- для предотвращения сильных связей между объектами системы;
- для наблюдения за состоянием определенных объектов;
Первый реализовывается.

Класс BudgetCalculator - один. Транзакций - много. Я бы в обратную сторону сделал.
Может я ошибаюсь и узко понимаю роль Наблюдателя.

2018-09-14 11:31 UTC, michael-java commented on Tracks/Zaqwesx/lesson10/Observed.java
> +    void removeObserver(Observer observer);
не нашел, где используется метод: void removeObserver(Observer observer);

2018-09-14 11:31 UTC, michael-java commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +public class MockingTranList {
по-моему это не mock тесты...

2018-09-14 11:31 UTC, michael-java commented on Tracks/Zaqwesx/lesson10/NotCvsException.java
> +    public NotCvsException(String message) { super(message); }
cs

2018-09-14 17:16 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +public class MockingTranList {
Да, Михаил, ты прав.  Непонятно что это такое

2018-09-14 17:16 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/Observed.java
> +public interface Observed {
Лучше назвать IDataSource

2018-09-14 17:17 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    private List<Transaction> transactions_ = new ArrayList<Transaction>();
Лучше такое делать в конструкторе

2018-09-14 17:18 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +        int cash;
Инкапсуляция!

2018-09-14 17:30 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/BudgetCalculator.java
> +public class BudgetCalculator implements Observer {
Лучше здесь использовать анонимный класс

2018-09-14 17:31 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/BudgetCalculator.java
> +        int balance = 0;
Вот это лучше сделать полем и список тоже сохранить

2018-09-20 12:03 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +    public void doMockTest() {
Тесты не содержаться внутри мок-класса

2018-09-20 12:04 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +    private final TransactionList.Transaction tranOne = new TransactionList.Transaction("21.08.2018;100000;Аванс;Зарплата");
Конкретные данные для теста тоже не содержаться внутри мок-класса

2018-09-20 12:04 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +        calculate();
А calculate зачем?

2018-09-20 12:15 UTC, olerysc requested changes

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +    private final TransactionList.Transaction tranOne = new TransactionList.Transaction("21.08.2018;100000;Аванс;Зарплата");
Максимум разные методы  для загрузки разных сценариев, но точно не члены класса

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockingTranList.java
> +    private void calculate() {
Выглядит как дублирование бизнес логики

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    static class Transaction {
Класс транзакция должен содержать все данные а не только те, которые нужны для твоего решения.  А вдруг бизнес-логике еще что-то понадобится?

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    public void addObserver(Observer observer) {
По умолчанию add и remove повторяют интерфейс контейнера, то есть имеют возвращаемое значение boolean

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    public void removeObserver(Observer observer) {
По умолчанию add и remove повторяют интерфейс контейнера, то есть имеют возвращаемое значение boolean

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    public void removeTransaction(String text) {
По умолчанию add и remove повторяют интерфейс контейнера, то есть имеют возвращаемое значение boolean

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    public void addTransaction(String text) {
По умолчанию add и remove повторяют интерфейс контейнера, то есть имеют возвращаемое значение boolean

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    public void addTransaction(Transaction transaction) {
По умолчанию add и remove повторяют интерфейс контейнера, то есть имеют возвращаемое значение boolean

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/TransactionList.java
> +    public List<Transaction> getTransactions_() {
ОООО, выглядит как нарушение инкапсуляции

2018-09-20 12:15 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/BudgetCalculator.java
> +public class BudgetCalculator implements Observer {
Очень маленький класс, который еще нарушает инкапсуляцию TransactionList. Это все подводит к тому, что ввод сущности не обоснован.

2018-10-18 10:56 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/CsvFileTransactionLoader.java
> +        this.observers_.remove(observer);
А если нет объекта в списке?

2018-10-18 10:56 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/CsvFileTransactionLoader.java
> +        this.observers_.add(observer);
А если есть?

2018-10-18 11:02 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/CsvFileTransactionLoader.java
> +        this.observers_.add(observer);
Если есть один и тот же observer, то будет двойная нотификации - и при логики рассчета будет неправильно

2018-10-18 14:46 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/MockTransactionLoader.java
> +public class MockTransactionLoader implements Observed{
Очень много общего кода с CsvFileTransactionLoader, вынести в абстрактный класс не пробовал?

2018-10-19 01:51 UTC, Zaqwesx commented on Tracks/Zaqwesx/lesson10/CsvFileTransactionLoader.java
> +        this.observers_.remove(observer);
на нет и суда нет. нужно как-то посигналить об этом?

2018-11-08 20:22 UTC, olerysc commented on Tracks/Zaqwesx/lesson10/DataLoader.java
> +        for (Observer obs : this.observers_) {
У коллекции есть метод contains - не надо писать такой код

2018-11-22 19:31 UTC, olerysc approved these changes

2018-11-22 19:31 UTC, merged